services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - "./app"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db

  redis:
    image: redis

  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: "afrovivo@9023"
    