services:
  app:
    build:
      dockerfile: Dockerfile
    command: "npm start"  
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db

  redis:
    image: redis

  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    