services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    command: "npm run start"  
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db

  redis:
    image: redis

  db:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: afrovivo_db
      

